### ISSUE TITLE
Call by value vs. call by reference

### ISSUE THREAD

**Issue by FrankHB** [taocpp/operators#6] opened 2016-02-26 04:20 UTC
Sometimes it is intended to pass the parameters by value rather than by reference. For example, to use with an odr-used object of literal type which is declared with `constexpr` but without a definition. If it is passed by reference, lvalue-to-rvalue conversion makes it odr-used, and the definition is needed to meet the One Definition Rule. Can this be configured by template arguments?

**Comment by d-frey** [comment] 2016-02-27 12:54
I'm not sure I understand the full impact of what you are suggesting. Could you elaborate, preferably with real code as an example?

Some things I am wondering about:

* Would you expect the operators to be marked `constexpr` (as this might become possible with C++14, but it is not easily possible to just add `constexpr` to them)?
* Do you only need to change the way a parameter is passed? Or also the overload set and the implementation as well? How would an ideal implementation look like in your opinion?
* Do you think your case is common or more like an exception? (Might influence how the API should then look like)

**Comment by FrankHB** [comment] 2016-02-28 06:05
For example, to implement something like `std::experimental::basic_string_view` comparison operations with `constexpr` (though strictly speaking this is not conforming, but still acceptable in several cases), and then using objects declared in class definition with `static constexpr` as parameters. If passed by reference, I still need to write additional definition for it.

```
template<typename C>
class string_utils
{
    static constexpr string_view empty = basic_string_view<C>();

    static constexpr bool is_empty(basic_string_view<C> sv)
    {
        return sv == empty;
    }
}
```

> Would you expect the operators to be marked constexpr (as this might become possible with C++14, but it is not easily possible to just add constexpr to them)?

Yes. This will be definitely beneficial. I think it is not too hard, though it requires some code to detect compiler support. I actually have implemented [my (compact) version](https://bitbucket.org/FrankHB/yslib/src/2824dc90d869be7246b14abb6332e1997dd34a63/YBase/include/ystdex/operators.hpp?at=master&fileviewer=file-view-default#operators.hpp-43) (spelled [`yconstfn`](https://bitbucket.org/FrankHB/yslib/src/2824dc90d869be7246b14abb6332e1997dd34a63/YBase/include/ydef.h?at=master&fileviewer=file-view-default#ydef.h-613) for portability). And since many implementations requires only one `return` statement, it also works for C++11.

> Do you only need to change the way a parameter is passed? Or also the overload set and the implementation as well? How would an ideal implementation look like in your opinion?
I currently only need the former. The problem is I can't figure out how an ideal implementation will look like to be, even the use cases are clear. (An easy but dirty design: to copy & paste, provide one more similar set of APIs?) This is an open question.

> Do you think your case is common or more like an exception?
I don't think it is common currently, but it should not be an exception. In [N4529](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/n4529.html) there already are two class templates with pass-by-value parameters in their comparison operations, i.e. `basic_string_view` and `observer_ptr`. Though I can only find the actual usability problem with `constexpr`, it is still reasonable to allow users controlling how parameters are passed in some explicit ways. Anyway, passing parameters by value itself is not rare in common practice.

BTW, my implementations of [`basic_string_view`](https://bitbucket.org/FrankHB/yslib/src/2824dc90d869be7246b14abb6332e1997dd34a63/YBase/include/ystdex/string_view.hpp?at=master&fileviewer=file-view-default#string_view.hpp-49), [`observer_ptr`](https://bitbucket.org/FrankHB/yslib/src/2824dc90d869be7246b14abb6332e1997dd34a63/YBase/include/ystdex/memory.hpp?at=master&fileviewer=file-view-default#memory.hpp-890), [`optional`](https://bitbucket.org/FrankHB/yslib/src/2824dc90d869be7246b14abb6332e1997dd34a63/YBase/include/ystdex/optional.h?at=master&fileviewer=file-view-default#optional.h-257) and [many iterator adaptors](https://bitbucket.org/FrankHB/yslib/src/2824dc90d869be7246b14abb6332e1997dd34a63/YBase/include/ystdex/iterator.hpp?at=master&fileviewer=file-view-default) with [encapsulated iterator operations](https://bitbucket.org/FrankHB/yslib/src/2824dc90d869be7246b14abb6332e1997dd34a63/YBase/include/ystdex/iterator_op.hpp?at=master&fileviewer=file-view-default#iterator_op.hpp-191) all rely on the operators. Many of them are ideal with pass-by-value parameters, if written manually.

**Comment by d-frey** [comment] 2016-03-06 11:30
> On 28.02.2016, at 07:05, FrankHB <notifications@github.com> wrote:
> 
> Would you expect the operators to be marked constexpr (as this might become possible with C++14, but it is not easily possible to just add constexpr to them)?
> 
> Yes. This will be definitely beneficial. I think it is not too hard, though it requires some code to detect compiler support. I actually have implemented my (compact) version (spelled yconstfn for portability). And since many implementations requires only one return statement, it also works for C++11.

The problem is not to detect whether or not the compiler supports constexpr, but if a given class does. Consider:

    struct Wrap
    {
        int value;

        // Wrap( int v ) : value(v) {}

        constexpr Wrap& operator*=(Wrap const& rhs)
        { value *= rhs.value; return *this; }

        friend constexpr Wrap operator * (Wrap const& lhs, Wrap const& rhs)
        {
            Wrap nrv{lhs};
            nrv *= rhs;
            return nrv;
        }
    };

When you comment out the constructor, everything is fine. But when a class does have a constructor like the above, the compiler will bail. Since I’m going for a generic solution, I need to support the non-constexpr-case as well. If you can come up with a solution to either have a generic implementation that works for both or how to detect constexpr-capable classes, I think we are out of luck.

FWIW, you can currently add constexpr support and experiment with it quite easily:

#include <utility>
// add “constexpr” to all generated operators, use C++14 (or newer) to compile
#define friend friend constexpr
// rename namespace to avoid conflicts, use tao::constexpr_operators::addable<>, etc.
#define operators constexpr_operators
#include <tao/operators.hpp>
#undef friend
#undef operators

But of course you won’t get a guarantee for the future on that :)

**Comment by d-frey** [comment] 2016-03-06 11:34
> Would you expect the operators to be marked constexpr (as this might become possible with C++14, but it is not easily possible to just add constexpr to them)?
> 
> Yes. This will be definitely beneficial. I think it is not too hard, though it requires some code to detect compiler support. I actually have implemented my (compact) version (spelled yconstfn for portability). And since many implementations requires only one return statement, it also works for C++11.

The problem is not to detect whether or not the compiler supports constexpr, but if a given class does. Consider:

    struct Wrap
    {
        int value;

        // Wrap( int v ) : value(v) {}

        constexpr Wrap& operator*=(Wrap const& rhs)
        { value *= rhs.value; return *this; }

        friend constexpr Wrap operator * (Wrap const& lhs, Wrap const& rhs)
        {
            Wrap nrv{lhs};
            nrv *= rhs;
            return nrv;
        }
    };

When you comment out the constructor, everything is fine. But when a class does have a constructor like the above, the compiler will bail. Since I’m going for a generic solution, I need to support the non-constexpr-case as well. If you can come up with a solution to either have a generic implementation that works for both or how to detect constexpr-capable classes, I think we are out of luck.

FWIW, you can currently add constexpr support and experiment with it quite easily:

    #include <utility>
    // add “constexpr” to all generated operators, use C++14 (or newer) to compile
    #define friend friend constexpr
    // rename namespace to avoid conflicts, use tao::constexpr_operators::addable<>, etc.
    #define operators constexpr_operators
    #include <tao/operators.hpp>
    #undef friend
    #undef operators

But of course you won’t get a guarantee for the future on that :)

**Comment by FrankHB** [comment] 2016-03-08 06:32
Ah, I missed that the declared friends can never be templates, nor `= default`. Thus according to [dcl.constexpr]/5, "the program is ill-formed; no diagnostic required", if no argument can make the invocation as a core constant expression. This is exactly the difficulty which you illustrated, except that the compiler can pretend it is correct...

And [macro.names]/2 forbids the macro trick, though they might actually work. It is definitely a hack.

Perhaps some `is_literal` check would work?

Too bad the core language is playing black magic that can't touched by library authors easily :(

**Comment by FrankHB** [comment] 2016-03-27 14:51
I'd note here the `constexpr` issue on friend functions of a class template has been [realized by others](https://groups.google.com/a/isocpp.org/forum/#!topic/std-discussion/vr6kI16078o). The standard is clearly flawed in this aspect. I'll use the need here as a proof of significance for that discussion.

**Comment by d-frey** [comment] 2016-03-27 14:59
As unfortunate as it is, I don't see any way to support `constexpr` with taocpp/operators. I'll close this issue, feel free to re-open or write an email when you have an idea how to provide reasonable support which does not break existing uses.

**Closed by d-frey** 2016-03-27 14:59 UTC

**Comment by FrankHB** [comment] 2016-04-11 03:55
@d-frey I found the suggested workaround in the [post](https://groups.google.com/a/isocpp.org/forum/#!topic/std-discussion/vr6kI16078o) not conflict to the compatibility, but a bit hard to implement (even I've worked out a [far more sophisticated strategy-based dispatching implementation](https://bitbucket.org/FrankHB/yslib/src/480b7866ade4dc6e7745751d0239abb269cb16d8/YBase/include/ystdex/operators.hpp?at=master) now). Now I work around another: by putting `template<typename = void>` before friend declarations. It also allows derived classes to "override" the friends. Please evaluate if it is appropriate.
It seems that GitHub does not allow me to re-open the issue because it is not closed by me...
